name: Deploy Microservice to ECS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: [self-hosted, linux, x64, devops]

    env:
      AWS_REGION: ap-south-1
      AWS_ACCOUNT_ID: 506115905612

      ECR_REPO: devops-sam-microservice
      ECR_URI: 506115905612.dkr.ecr.ap-south-1.amazonaws.com/devops-sam-microservice

      ECS_CLUSTER: devops-sam-ecs-cluster
      ECS_SERVICE: devops-sam-microservice
      TASK_FAMILY: devops-sam-microservice
      EXECUTION_ROLE_ARN: arn:aws:iam::506115905612:role/devops-sam-ecs-execution-role

    steps:
      # 1️⃣ Checkout code
      - name: Checkout source
        uses: actions/checkout@v4

      # 2️⃣ Configure AWS (OIDC – NO KEYS)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ap-south-1

      # 3️⃣ Login to ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
          | sudo docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      # 4️⃣ Build & Push Docker Image
      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=${GITHUB_SHA}
          IMAGE_URI=$ECR_URI:$IMAGE_TAG

          sudo docker build -t $IMAGE_URI .
          sudo docker push $IMAGE_URI

          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      # 5️⃣ Register NEW ECS Task Definition
      - name: Register new Task Definition
        run: |
          cat > task-def.json <<EOF
          {
            "family": "$TASK_FAMILY",
            "networkMode": "awsvpc",
            "requiresCompatibilities": ["FARGATE"],
            "cpu": "256",
            "memory": "512",
            "executionRoleArn": "$EXECUTION_ROLE_ARN",
            "containerDefinitions": [
              {
                "name": "microservice",
                "image": "$IMAGE_URI",
                "essential": true,
                "portMappings": [
                  { "containerPort": 3000 }
                ]
              }
            ]
          }
          EOF

          aws ecs register-task-definition \
            --cli-input-json file://task-def.json

      # 6️⃣ Update ECS Service (Rolling Deploy)
      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service $ECS_SERVICE \
            --task-definition $TASK_FAMILY
